### ISSUE TITLE
Bug when using the mod and High Command

### ISSUE THREAD

**Issue by Yivas** [Crowdedlight/Crows-Electronic-Warfare#110] opened 2024-10-17 17:32 UTC
There is a very strange bug that started to happen to me, when I started to use High command in my games, for some reason when selecting the reasons on the map, besides the beep that should be there, there was a longer and more serious one, when I tested that without mods this did not happen, I was testing one by one and I ended up finding that it was with this specific mod.

**Comment by b-mayr-1984** [comment] 2024-10-18 01:06
> [..] when selecting the reasons on the map

What do you mean by that?
How do you select _reasons_ on a map?

**Comment by Yivas** [comment] 2024-10-18 10:23
Oh sorry sorry XD, when selecting the Units on the map, in [this](https://youtu.be/Vl4n-Cm2Jng?si=TkpnXLFbTvDNyfQc&t=154) video you can see how it should sound, but when using Crows Electronic Warfare sounds like this

https://github.com/user-attachments/assets/eaecc8be-eadb-4e79-8a2e-dd64f42598df

**Comment by Crowdedlight** [comment] 2024-10-19 10:40
Ah, I think that might be because I did not have prefixes added to the defined sounds. So I might have used the same classname for the sound as High Command and overridden them. If that is the cause this should be fixed in #105. 

I am planning on releasing an update this weekend, please try and test again when that update is out and let me know if that fixed it

**Closed** 2024-10-28 21:46 UTC
