### ISSUE TITLE
Script error immediately when starting (profiling branch)

### ISSUE THREAD

**Issue by Filip-88** [Crowdedlight/Crows-Electronic-Warfare#103] opened 2024-07-23 14:02 UTC
Im getting the following error when using only this mod (and dependencies), to test i managed to reproduce it by only placing a single playable unit start the scenario in the editor.

I am using the latest Arma3 profiling branch if that matters.
Edit: seems like the error does not appear on the normal branch of the game.
```
"CrowsEW:fnc_zeusRegister: Zeus initialization complete. Zeus Enhanced Detected: "
Error in expression <} forEach _contextActionList;

diag_log format ["CrowsEW:fnc_zeusRegister: Zeus >
   Error position: <format ["CrowsEW:fnc_zeusRegister: Zeus >

   Error 1 elements provided, 2 expected
File /z/crowsEW/addons/zeus/functions/fnc_zeusRegister.sqf..., line 324
```

[logfile.zip](https://github.com/user-attachments/files/16349915/logfile.zip)

**Comment by b-mayr-1984** [comment] 2024-07-23 14:32
@Filip-88 thanks for the comprehensive report. It is much better prepared to what I am used too. 🙂👍

This seems to be a duplicate of https://github.com/Crowdedlight/Crows-Electronic-Warfare/issues/101 .

@dedmen made a change on the  profiling branch, which causes stricter validation and raises this error message 

https://github.com/Crowdedlight/Crows-Electronic-Warfare/pull/102 will fix the issue, but is not part of a release yet. 
See also https://github.com/Crowdedlight/Crows-Electronic-Warfare/issues/101#issuecomment-2241671281

**Closed by b-mayr-1984** 2024-07-23 14:32 UTC
